apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: springboot-docker
  name: springboot-docker
  namespace: cscec-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      component: springboot-docker
  template:
    metadata:
      labels:
        component: springboot-docker
    spec:
      containers:
        - image: $REGISTRY/$HARBOR_PROJECT/$APP_NAME:snapshot-$BUILD_NUMBER
          imagePullPolicy: IfNotPresent
          name: springboot-docker
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30