apiVersion: v1
kind: Service
metadata:
  labels:
    component: springboot-docker
  name: springboot-docker
  namespace: project-demo-dev
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32555
  selector:
    component: springboot-docker
  sessionAffinity: None
  type: NodePort
